version: "3"
services:
  storage:
    image: alexeybelous/mongo:1.0
    restart: always
    environment:
      - MONGODB_ADMIN_USER=${MONGODB_ADMIN_USER}
      - AUTH=yes
      - MONGODB_ADMIN_PASS=${MONGODB_ADMIN_PASS}
      - MONGODB_APPLICATION_DATABASE=fundssplitter
      - MONGODB_APPLICATION_USER=fundssplitter
      - MONGODB_APPLICATION_PASS=${MONGODB_ADMIN_PASS}
    container_name: storage
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongodb_data:/data
  app:
    image: mcr.microsoft.com/dotnet/core/runtime:2.2
    restart: always
    container_name: app
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: dotnet FundsSplitter.App.dll
    depends_on:
      - "storage"
    ports:
      - "8443:8443"
