<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AsyncResult.fs" />
    <Compile Include="Logging.fs" />
    <Compile Include="Storage.fs" />
    <Compile Include="Strings.fs" />
    <Compile Include="Transactions/Types.fs" />
    <Compile Include="Transactions/CrudOperations.fs" />
    <Compile Include="Transactions/ProcessingLogic.fs" />
    <Compile Include="Analytics/Types.fs" />
    <Compile Include="Analytics/Storage.fs" />
  </ItemGroup>

</Project>
