<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="./appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FundsSplitter.Logic\FundsSplitter.Logic.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Data" Version="6.4.0" />
    <PackageReference Include="Giraffe" Version="6.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.2.0" />
    <PackageReference Include="Telegram.Bot" Version="19.0.0" />
  </ItemGroup>
</Project>