name: Deploy

on:
  push:
    branches: [master]
  # deployment:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.103
      - name: Publish
        run: ./publish.sh

      - name: Inject config.json
        run: "echo $PROD_CONFIG >> ./publish/app/config.json"
        env:
          PROD_CONFIG: ${{secrets.PROD_CONFIG}}
        shell: bash
      - name: Inject ENV
        run: "echo $PROD_ENV >> ./publish/env"
        env:
          PROD_ENV: ${{secrets.PROD_ENV}}
        shell: bash

      - name: Compress artifacts
        run: tar -czf ./package.tar.gz ./publish/**
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRODSSH }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./package.tar.gz"
          REMOTE_HOST: ${{ secrets.PROD_HOSTNAME }}
          REMOTE_USER: ${{ secrets.PROD_USERNAME }}
          REMOTE_PORT: ${{ secrets.PROD_PORT }}
          TARGET: /app
      - name: Restart app
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.PROD_HOSTNAME }}
          username: ${{ secrets.PROD_USERNAME }}
          privateKey: ${{ secrets.PRODSSH }}
          port: 1122
          command: "cd /app && docker-compose down && tar -zxvf ./package.tar.gz && cp -r ./publish/** ./ && rm -rf ./publish && rm -rf ./package.tar.gz && mv ./env ./.env && docker-compose up -d"
